// Keyword-to-Category and Coordinate Centroid configuration for the Bubble Chart

export const tickerToKeyword = {
  // Underlying stocks (Extracted from single asset ETFs)
  'AAAU': 'Goldman Sachs Physical Gold Shares',
  'AAL': 'American Airlines',
  'AAOI': 'Applied Optoelectronics',
  'AAPL': 'Apple',
  'ABNB': 'Airbnb',
  'ACHR': 'Archer Aviation',
  'ADBE': 'Adobe',
  'AETH': 'Bitwise Trendwise Ether And Treasuries Rotation Strategy',
  'AFRM': 'Affirm Holdings',
  'AG': '21shares Ag',
  'AGQ': 'Proshares Ultra Silver',
  'AI': 'C3.ai',
  'ALAB': 'Astera Labs',
  'ALB': 'Albemarle',
  'AMAT': 'Applied Materials',
  'AMD': 'AMD',
  'AMKR': 'Amkor Technology',
  'AMPX': 'Amprius Technologies',
  'AMZN': 'Amazon',
  'ANET': 'Arista Networks',
  'APH': 'Amphenol',
  'APLD': 'Applied Digital',
  'APP': 'AppLovin',
  'ARK': 'Ark 21shares Bitcoin',
  'ARM': 'Arm Holdings',
  'ASML': 'ASML',
  'ASTS': 'AST SpaceMobile',
  'AVAV': 'AeroVironment',
  'AVAZ': '2x Avalanche',
  'AVGO': 'Broadcom',
  'AXP': 'American Express',
  'AXTI': 'AXT Inc.',
  'BA': 'Boeing',
  'BABA': 'Alibaba',
  'BAGY': 'Amplify Bitcoin Max Income Covered Call',
  'BAR': 'Graniteshares Gold Trust Shares Of Beneficial Interest',
  'BAVA': 'Bitwise Avalanche',
  'BBAI': 'BigBear.ai',
  'BCCC': 'Global X Bitcoin Covered Call',
  'BE': 'Bloom Energy',
  'BHYP': 'Bitwise Hyperliquid',
  'BIDU': 'Baidu',
  'BITB': 'Bitwise Bitcoin',
  'BITC': 'Bitwise Trendwise Bitcoin And Treasuries Rotation Strategy',
  'BITI': 'Proshares Short Bitcoin',
  'BITO': 'Proshares Bitcoin',
  'BITU': 'Proshares Ultra Bitcoin',
  'BITX': '2x Bitcoin Strategy',
  'BITY': 'Amplify Bitcoin 2% Monthly Option Income',
  'BLSH': 'Bullish',
  'BMNR': 'Bitmine Immersion',
  'BNB': 'Binance Coin',
  'BNO': 'United States Brent Oil Fund, Lp Etv',
  'BOIL': 'Proshares Ultra Bloomberg Natural Gas',
  'BP': 'BP',
  'BRK': 'Berkshire Hathaway',
  'BRKB': 'Berkshire Hathaway',
  'BRRR': 'Coinshares Bitcoin',
  'BSOL': 'Bitwise Solana Staking',
  'BTC': 'Bitcoin',
  'BTCC': 'Grayscale Bitcoin Covered Call',
  'BTCL': 'Bitcoin',
  'BTCO': 'Invesco Galaxy Bitcoin',
  'BTCW': 'Wisdomtree Bitcoin Fund',
  'BTCZ': 'Bitcoin',
  'BU': 'Barrick Gold',
  'BULL': 'Webull',
  'BWOW': 'Bitwise Dogecoin',
  'CANE': 'Teucrium Sugar Fund Etv',
  'CAT': 'Caterpillar',
  'CBOA': 'Calamos Bitcoin Structured Alt Protection - April',
  'CBOJ': 'Calamos Bitcoin Structured Alt Protection - January',
  'CBOO': 'Calamos Bitcoin Structured Alt Protection - October',
  'CBOY': 'Calamos Bitcoin Structured Alt Protection - July',
  'CBRS': 'Cerebras Systems',
  'CBTA': 'Calamos Bitcoin 80 Series Structured Alt Protection - April',
  'CBTJ': 'Calamos Bitcoin 80 Series Structured Alt Protection - January',
  'CBTO': 'Calamos Bitcoin 80 Series Structured Alt Protection - October',
  'CBTY': 'Calamos Bitcoin 80 Series Structured Alt Protection - July',
  'CBXA': 'Calamos Bitcoin 90 Series Structured Alt Protection - April',
  'CBXJ': 'Calamos Bitcoin 90 Series Structured Alt Protection - January',
  'CBXO': 'Calamos Bitcoin 90 Series Structured Alt Protection - October',
  'CBXY': 'Calamos Bitcoin 90 Series Structured Alt Protection - July',
  'CEG': 'Constellation Energy',
  'CGBCF': 'Ci Investments Inc Galaxy Bitcoin',
  'CHNL': 'Chainlink',
  'CHNU': '2x Chainlink',
  'CIEN': 'Ciena',
  'CIFR': 'Cipher Mining',
  'CLNK': 'Bitwise Chainlink',
  'CLS': 'Celestica',
  'CLSK': 'CleanSpark',
  'CMG': 'Chipotle Mexican Grill',
  'CNC': 'Centene',
  'COHR': 'Coherent',
  'COIN': 'Coinbase',
  'CORN': 'Teucrium Corn Fund Etv',
  'CORZ': 'Core Scientific',
  'COST': 'Costco',
  'CPER': 'Copper',
  'CPNG': 'Coupang',
  'CRCL': 'Circle',
  'CRDD': 'Cardano',
  'CRDO': 'Credo Technology',
  'CRDX': '2x Cardano',
  'CRM': 'Salesforce',
  'CRML': 'Critical Metals',
  'CRUDE': 'Global X Investments Canada Inc. Betapro Crude Oil Inverse Leveraged Dail',
  'CRWD': 'CrowdStrike',
  'CRWV': 'CoreWeave',
  'CSCO': 'Cisco',
  'CTWO': 'Common',
  'CVNA': 'Carvana',
  'CXRN': 'Teucrium 2x Daily Corn',
  'DB': 'Db Gold Short Etn Due February 15, 2038',
  'DEFI': 'Hashdex Bitcoin',
  'DELL': 'Dell Technologies',
  'DIS': 'Disney',
  'DJT': 'Trump Media & Tech',
  'DKNG': 'DraftKings',
  'DNN': 'Denison Mines',
  'DOGE': 'Dogecoin',
  'DULL': 'Microsectors Gold -3x Inverse Leveraged Etns Due January 29, 2043',
  'DUOL': 'Duolingo',
  'EETH': 'Proshares Ether',
  'EHCC': 'Global X Ethereum Covered Call',
  'EHY': 'Amplify Ethereum Max Income Covered Call',
  'EOSE': 'Eos Energy',
  'ETCO': 'Grayscale Ethereum Covered Call',
  'ETH': 'Ethereum',
  'ETHA': 'Ishares Ethereum Trust',
  'ETHB': 'Ishares Staked Ethereum Trust',
  'ETHD': 'Proshares Ultrashort Ether',
  'ETHE': 'Grayscale Ethereum Staking Shares',
  'ETHER': 'Purpose Investments Inc. Ether Non Currency Hedge Unit',
  'ETHT': 'Proshares Ultra Ether',
  'ETHU': '2x Ether',
  'ETHV': 'Vaneck Ethereum',
  'ETHW': 'Bitwise Ethereum',
  'ETHXF': 'Ci Investments Inc Galaxy Ethereum',
  'ETN': 'Eaton',
  'ETOR': 'eToro',
  'ETTY': 'Amplify Ethereum 3% Monthly Option Income',
  'ETU': 'Ether',
  'EUO': 'Proshares Ultrashort Euro',
  'EZBC': 'Franklin Templeton Digital Holdings Trust Shares Of Franklin Bitcoin',
  'EZET': 'Franklin Ethereum',
  'FBTC': 'Fidelity Wise Origin Bitcoin Fund',
  'FCX': 'Freeport-McMoRan',
  'FD': 'Purpose Investments Inc. Silver Bullion Fd Non Currency Hedge',
  'FETH': 'Fidelity Ethereum Fund',
  'FGDL': 'Franklin Responsibly Sourced Gold',
  'FIG': 'Fortress Transportation',
  'FIGR': 'Figure Acquisition',
  'FLY': 'Flywire',
  'FSOL': 'Fidelity Solana Fund',
  'FT': 'Ft Vest Bitcoin Strategy Floor15 July',
  'FUTU': 'Futu Holdings',
  'FXA': 'Invesco Currencyshares Australian Dollar Trust',
  'FXB': 'Invesco Currencyshares British Pound Sterling Trust',
  'FXC': 'Invesco Currencyshares Canadian Dollar Trust',
  'FXE': 'Invesco Currencyshares Euro Currency Trust',
  'FXF': 'Invesco Currencyshares Swiss Franc Trust',
  'FXY': 'Invesco Currencyshares Japanese Yen Trust',
  'GAVA': 'Grayscale Avalanche Staking',
  'GBTC': 'Grayscale Bitcoin Trust',
  'GDOG': 'Grayscale Dogecoin Trust',
  'GEMI': 'Gemi Daily',
  'GEV': 'GE Vernova',
  'GLD': 'Gold',
  'GLDM': 'Spdr Gold Minishares Trust',
  'GLL': 'Proshares Ultrashort Gold',
  'GLNK': 'Grayscale Chainlink Trust',
  'GLW': 'Corning',
  'GLXY': 'Galaxy Digital',
  'GME': 'GameStop',
  'GOOGL': 'Google',
  'GRAB': 'Grab Holdings',
  'GROUP': 'Evolve Funds Group Inc.',
  'GSK': 'Gsk Plc',
  'GSOL': 'Grayscale Solana Staking',
  'GSUI': 'Grayscale Sui Staking',
  'HBAR': 'Canary Hbar',
  'HBTC': 'Fortuna Hedged Bitcoin',
  'HIMS': 'Hims & Hers Health',
  'HL': 'Hecla Mining',
  'HODL': 'Vaneck Bitcoin Trust',
  'HON': 'Honeywell',
  'HOOD': 'Robinhood',
  'HUT': 'Hut 8 Mining',
  'HYPE': '21shares Hype',
  'IAU': 'Ishares Gold Trust Shares',
  'IAUM': 'Ishares Gold Trust Micro Shares',
  'IBIT': 'Ishares Bitcoin Trust',
  'IBM': 'IBM',
  'INTC': 'Intel',
  'IONQ': 'IonQ',
  'IREN': 'Iris Energy',
  'ISRG': 'Intuitive Surgical',
  'JD': 'Kraneshares Jd Daily',
  'JOBY': 'Joby Aviation',
  'JP': 'JPMorgan Chase',
  'KCCA': 'Kraneshares California Carbon Allowance Strategy',
  'KEEL': 'Keel',
  'KGLD': 'Kurv Gold Enhanced Income',
  'KLAC': 'KLA Corp',
  'KOLD': 'Proshares Ultrashort Bloomberg Natural Gas',
  'KSLV': 'Kurv Silver Enhanced Income',
  'KTOS': 'Kratos Defense',
  'LAC': 'Lithium Americas',
  'LCID': 'Lucid Group',
  'LEU': 'Centrus Energy',
  'LITE': 'Lumentum Holdings',
  'LLY': 'Eli Lilly',
  'LMND': 'Lemonade',
  'LMT': 'Lockheed Martin',
  'LRCX': 'Lam Research',
  'LTCC': 'Canary Litecoin',
  'LULU': 'Lululemon',
  'LUNR': 'Intuitive Machines',
  'MARA': 'MARA Holdings',
  'MELI': 'MercadoLibre',
  'META': 'Meta',
  'MP': 'MP Materials',
  'MPWR': 'Monolithic Power',
  'MRNA': 'Moderna',
  'MRVL': 'Marvell Technology',
  'MSBT': 'Common',
  'MSFT': 'Microsoft',
  'MSTR': 'MicroStrategy',
  'MU': 'Micron Technology',
  'NBIS': 'Nbis Daily',
  'NEM': 'Newmont Mining',
  'NEOS': 'Neos Gold High Income',
  'NET': 'Cloudflare',
  'NFLX': 'Netflix',
  'NIO': 'Nio',
  'NOK': 'Nokia',
  'NOW': 'ServiceNow',
  'NU': 'Nu Holdings',
  'NV': 'Stmicroelectronics Nv',
  'NVDA': 'NVIDIA',
  'NVO': 'Novo Nordisk',
  'NVOH': 'Novo Nordisk A/s B Shares',
  'NVTS': 'Navitas Semiconductor',
  'OARK': 'Innovation',
  'OBIL': 'Us Treasury 12 Month Bill',
  'OBTC': 'Osprey Bitcoin Trust',
  'OILK': 'Proshares K-1 Free Crude Oil',
  'OKLO': 'Oklo Inc.',
  'OKTA': 'Okta',
  'ONDS': 'Ondas Inc.',
  'OPEN': 'Opendoor',
  'ORCL': 'Oracle',
  'ORLY': 'O\'Reilly Automotive',
  'OSCR': 'Oscar Health',
  'OUNZ': 'Vaneck Merk Gold',
  'PAAS': 'Pan American Silver',
  'PALL': 'Abrdn Physical Palladium Shares',
  'PANW': 'Palo Alto Networks',
  'PATH': 'UiPath',
  'PBECF': 'Purpose Investments Inc. Bitcoin Cad Non Currency Hedged',
  'PBR': 'Petrobras',
  'PDD': 'Pinduoduo',
  'PL': 'Planet Labs',
  'PLTM': 'Graniteshares Platinum Shares',
  'PLTR': 'Palantir Technologies',
  'PLUG': 'Plug Power',
  'POET': 'Poet Technologies',
  'PONY': 'Pony.ai',
  'PPLT': 'Abrdn Physical Platinum Shares',
  'PRBEF': 'Purpose Investments Inc. Bitcoin Usd Non Currency Hedged',
  'PYPL': 'PayPal',
  'QBF': 'Innovator Uncapped Bitcoin 20 Floor - Quarterly',
  'QBTS': 'D-Wave Quantum',
  'QCOM': 'Qualcomm',
  'QETH': 'Invesco Galaxy Ethereum',
  'QS': 'QuantumScape',
  'QSOL': 'Invesco Galaxy Solana',
  'QUBT': 'Quantum Computing',
  'RBLX': 'Roblox',
  'RCAT': 'Red Cat Holdings',
  'RDDT': 'Reddit',
  'RDW': 'Redwire',
  'RGTI': 'Rigetti Computing',
  'RIOT': 'Riot Platforms',
  'RIVN': 'Rivian',
  'RKLB': 'Rocket Lab',
  'RKT': 'Rocket Companies',
  'ROYAL': 'Royal Canadian Mint Exch Traded Receipt',
  'RTX': 'RTX Corp',
  'SAP': 'Sap Se',
  'SATS': 'EchoStar',
  'SBET': 'Sbet',
  'SBIT': 'Proshares Ultrashort Bitcoin',
  'SBUX': 'Starbucks',
  'SCO': 'Proshares Ultrashort Bloomberg Crude Oil',
  'SCOP': 'Sprott Physical Copper Trust',
  'SETH': 'Proshares Short Ether',
  'SGOL': 'Abrdn Physical Gold Shares',
  'SHNY': 'Microsectors Gold 3x Leveraged Etns Due January 29, 2043',
  'SHOP': 'Shopify',
  'SIVR': 'Abrdn Physical Silver Shares',
  'SLON': 'Proshares Ultra Solana',
  'SLV': 'Silver',
  'SMCI': 'Super Micro Computer',
  'SMR': 'NuScale Power',
  'SNAP': 'Snap Inc.',
  'SNDK': 'SanDisk',
  'SNOW': 'Snowflake',
  'SOEZ': 'Franklin Solana',
  'SOFI': 'SoFi Technologies',
  'SOL': 'Solana',
  'SOLC': 'Canary Marinade Solana',
  'SOLM': 'Amplify Solana 3% Monthly Option Income',
  'SOLT': '2x Solana',
  'SOLZ': 'Solana',
  'SOUN': 'SoundHound AI',
  'SOYB': 'Teucrium Soybean Fund Etv',
  'SPOT': 'Spotify',
  'SRPT': 'Sarepta Therapeutics',
  'STLR': 'Stellar',
  'STLU': '2x Stellar',
  'STX': 'Seagate Technology',
  'SUI': 'Sui',
  'SUIL': '2x Sui',
  'TBIL': 'F/m Us Treasury 3 Month Bill Fund',
  'TCAN': '21shares Canton Network',
  'TDOG': '21shares Dogecoin',
  'TDOT': '21shares Polkadot',
  'TEM': 'Tempus AI',
  'TER': 'Teradyne',
  'TETH': '21shares Ethereum',
  'THYP': '21shares Hyperliquid',
  'TMH': 'Toyota Motor Corporation',
  'TSLA': 'Tesla',
  'TSM': 'Taiwan Semiconductor',
  'TSOL': '21shares Solana',
  'TSUI': '21shares Sui',
  'TTD': 'The Trade Desk',
  'TXN': 'Texas Instruments',
  'TXXD': '21shares Dogecoin',
  'TXXS': '21shares Sui',
  'UBER': 'Uber',
  'UCO': 'Proshares Ultra Bloomberg Crude Oil',
  'UCOP': 'Proshares Ultra Copper K-1 Free',
  'UEC': 'Uranium Energy',
  'UFIV': 'Us Treasury 5 Year Note',
  'UGA': 'Gasoline',
  'UGL': 'Proshares Ultra Gold',
  'ULE': 'Proshares Ultra Euro',
  'UNG': 'Natural Gas',
  'UNH': 'UnitedHealth',
  'UNL': 'United States 12 Month Natural Gas Fund',
  'UNX': 'Unity Software',
  'UPAL': 'Proshares Ultra Palladium K-1 Free',
  'UPLT': 'Proshares Ultra Platinum K-1 Free',
  'UPS': 'United Parcel Service',
  'UPST': 'Upstart Holdings',
  'USAR': 'USAR',
  'USL': 'United States 12 Month Oil',
  'USO': 'Crude Oil',
  'USVN': 'Us Treasury 7 Year Note',
  'UTEN': 'Us Treasury 10 Year Note',
  'UTHY': 'Us Treasury 30 Year Bond',
  'UTRE': 'Us Treasury 3 Year Note',
  'UTWO': 'Us Treasury 2 Year Note',
  'UTWY': 'Us Treasury 20 Year Bond',
  'UUUU': 'Energy Fuels',
  'UX': 'Uranium',
  'VALE': 'Vale SA',
  'VAVX': 'Vaneck Avalanche',
  'VIX': 'Vix Futures',
  'VRT': 'Vertiv',
  'VSOL': 'Vaneck Solana',
  'VST': 'Vst',
  'WDC': 'Western Digital',
  'WEAT': 'Teucrium Wheat Fund Etv',
  'WLDU': 'World Stock Daily',
  'WULF': 'TeraWulf',
  'WXET': 'Teucrium 2x Daily Wheat',
  'XBIL': 'Us Treasury 6 Month Bill',
  'XBTY': 'Graniteshares Bitcoin',
  'XEY': 'Graniteshares Ether',
  'XNDU': 'Xndu Daily',
  'XOM': 'Exxon Mobil',
  'XOVR': 'Private-Public Crossover',
  'XPEV': 'Xpeng',
  'XRP': 'XRP',
  'XYZ': 'Block',
  'YBIT': 'Bitcoin',
  'YCL': 'Proshares Ultra Yen',
  'YCS': 'Proshares Ultrashort Yen New',
  'YETH': 'Ether Covered Call Strategy',
  'ZETA': 'Zeta Global',
  'ZSL': 'Proshares Ultrashort Silver',

  // Broad Index / Sector ETFs (Manual mappings)
  'SMH': 'Semiconductors',
  'SOXX': 'Semiconductors',
  'SOXS': 'Semiconductors',
  'SOXL': 'Semiconductors',
  'QQQ': 'Tech',
  'XLK': 'Tech',
  'TECL': 'Tech',
  'XLE': 'Energy',
  'OIH': 'Energy',
  'XLU': 'Utilities',
  'ACES': 'Clean Energy',
  'XLF': 'Financials',
  'KRE': 'Regional Banks',
  'GLD': 'Gold',
  'IAU': 'Gold',
  'SLV': 'Silver',
  'USO': 'Crude Oil',
  'UNG': 'Natural Gas',
  'TLT': 'Long-term Bonds',
  'BND': 'Total Bond Market',
  'AGG': 'Total Bond Market',
  'HYG': 'High Yield Bonds',
  'JNK': 'High Yield Bonds',
  'LQD': 'Investment Grade Bonds',
  'MINT': 'Short-term Bonds',
  'BIL': 'T-Bills',
  'XLRE': 'Real Estate',
  'VNQ': 'Real Estate',
};

export const keywordToCategory = {
  // --- Consumer & Others ---
  'Airbnb': 'Consumer & Others',
  'Alibaba': 'Consumer & Others',
  'Amazon': 'Consumer & Others',
  'Calamos Bitcoin 80 Series Structured Alt Protection - April': 'Consumer & Others',
  'Calamos Bitcoin 80 Series Structured Alt Protection - January': 'Consumer & Others',
  'Calamos Bitcoin 80 Series Structured Alt Protection - July': 'Consumer & Others',
  'Calamos Bitcoin 80 Series Structured Alt Protection - October': 'Consumer & Others',
  'Calamos Bitcoin 90 Series Structured Alt Protection - April': 'Consumer & Others',
  'Calamos Bitcoin 90 Series Structured Alt Protection - January': 'Consumer & Others',
  'Calamos Bitcoin 90 Series Structured Alt Protection - July': 'Consumer & Others',
  'Calamos Bitcoin 90 Series Structured Alt Protection - October': 'Consumer & Others',
  'Calamos Bitcoin Structured Alt Protection - April': 'Consumer & Others',
  'Calamos Bitcoin Structured Alt Protection - January': 'Consumer & Others',
  'Calamos Bitcoin Structured Alt Protection - July': 'Consumer & Others',
  'Calamos Bitcoin Structured Alt Protection - October': 'Consumer & Others',
  'Carvana': 'Consumer & Others',
  'Centene': 'Consumer & Others',
  'Chipotle Mexican Grill': 'Consumer & Others',
  'Consumer': 'Consumer & Others',
  'Consumer discretionary': 'Consumer & Others',
  'Consumer staples': 'Consumer & Others',
  'Costco': 'Consumer & Others',
  'Coupang': 'Consumer & Others',
  'DraftKings': 'Consumer & Others',
  'Eli Lilly': 'Consumer & Others',
  'Ft Vest Bitcoin Strategy Floor15 July': 'Consumer & Others',
  'GameStop': 'Consumer & Others',
  'Gsk Plc': 'Consumer & Others',
  'Health care': 'Consumer & Others',
  'Healthcare': 'Consumer & Others',
  'Hims & Hers Health': 'Consumer & Others',
  'Innovation': 'Consumer & Others',
  'Innovator Uncapped Bitcoin 20 Floor - Quarterly': 'Consumer & Others',
  'Intuitive Surgical': 'Consumer & Others',
  'Kraneshares Jd Daily': 'Consumer & Others',
  'Lucid Group': 'Consumer & Others',
  'Lululemon': 'Consumer & Others',
  'MercadoLibre': 'Consumer & Others',
  'Moderna': 'Consumer & Others',
  'Nio': 'Consumer & Others',
  'Novo Nordisk': 'Consumer & Others',
  'Novo Nordisk A/s B Shares': 'Consumer & Others',
  'O\'Reilly Automotive': 'Consumer & Others',
  'Pinduoduo': 'Consumer & Others',
  'Private-Public Crossover': 'Consumer & Others',
  'QuantumScape': 'Consumer & Others',
  'Sarepta Therapeutics': 'Consumer & Others',
  'Sbet': 'Consumer & Others',
  'Starbucks': 'Consumer & Others',
  'Tesla': 'Consumer & Others',
  'Toyota Motor Corporation': 'Consumer & Others',
  'UnitedHealth': 'Consumer & Others',
  'Vix Futures': 'Consumer & Others',
  'World Stock Daily': 'Consumer & Others',
  'Xpeng': 'Consumer & Others',
  // --- Energy & Industrials ---
  'AeroVironment': 'Energy & Industrials',
  'Albemarle': 'Energy & Industrials',
  'American Airlines': 'Energy & Industrials',
  'Archer Aviation': 'Energy & Industrials',
  'BP': 'Energy & Industrials',
  'Bloom Energy': 'Energy & Industrials',
  'Boeing': 'Energy & Industrials',
  'Caterpillar': 'Energy & Industrials',
  'Centrus Energy': 'Energy & Industrials',
  'Clean Energy': 'Energy & Industrials',
  'Constellation Energy': 'Energy & Industrials',
  'Critical Metals': 'Energy & Industrials',
  'Denison Mines': 'Energy & Industrials',
  'Eaton': 'Energy & Industrials',
  'Energy': 'Energy & Industrials',
  'Energy Fuels': 'Energy & Industrials',
  'Eos Energy': 'Energy & Industrials',
  'Exxon Mobil': 'Energy & Industrials',
  'Freeport-McMoRan': 'Energy & Industrials',
  'GE Vernova': 'Energy & Industrials',
  'Grab Holdings': 'Energy & Industrials',
  'Hecla Mining': 'Energy & Industrials',
  'Honeywell': 'Energy & Industrials',
  'Industrials': 'Energy & Industrials',
  'Intuitive Machines': 'Energy & Industrials',
  'Joby Aviation': 'Energy & Industrials',
  'Kratos Defense': 'Energy & Industrials',
  'Lithium Americas': 'Energy & Industrials',
  'Lockheed Martin': 'Energy & Industrials',
  'MP Materials': 'Energy & Industrials',
  'Materials': 'Energy & Industrials',
  'Newmont Mining': 'Energy & Industrials',
  'NuScale Power': 'Energy & Industrials',
  'Oklo Inc.': 'Energy & Industrials',
  'Opendoor': 'Energy & Industrials',
  'Pan American Silver': 'Energy & Industrials',
  'Petrobras': 'Energy & Industrials',
  'Planet Labs': 'Energy & Industrials',
  'Plug Power': 'Energy & Industrials',
  'RTX Corp': 'Energy & Industrials',
  'Real Estate': 'Energy & Industrials',
  'Red Cat Holdings': 'Energy & Industrials',
  'Redwire': 'Energy & Industrials',
  'Rivian': 'Energy & Industrials',
  'Rocket Lab': 'Energy & Industrials',
  'USAR': 'Energy & Industrials',
  'Uber': 'Energy & Industrials',
  'United Parcel Service': 'Energy & Industrials',
  'Uranium Energy': 'Energy & Industrials',
  'Utilities': 'Energy & Industrials',
  'Vale SA': 'Energy & Industrials',
  'Vst': 'Energy & Industrials',
  // --- Financials & Macro ---
  '21shares Ag': 'Financials & Macro',
  '21shares Canton Network': 'Financials & Macro',
  '21shares Dogecoin': 'Financials & Macro',
  '21shares Ethereum': 'Financials & Macro',
  '21shares Hype': 'Financials & Macro',
  '21shares Hyperliquid': 'Financials & Macro',
  '21shares Polkadot': 'Financials & Macro',
  '21shares Solana': 'Financials & Macro',
  '21shares Sui': 'Financials & Macro',
  '2x Avalanche': 'Financials & Macro',
  '2x Bitcoin Strategy': 'Financials & Macro',
  '2x Cardano': 'Financials & Macro',
  '2x Chainlink': 'Financials & Macro',
  '2x Ether': 'Financials & Macro',
  '2x Solana': 'Financials & Macro',
  '2x Stellar': 'Financials & Macro',
  '2x Sui': 'Financials & Macro',
  'Abrdn Physical Gold Shares': 'Financials & Macro',
  'Abrdn Physical Palladium Shares': 'Financials & Macro',
  'Abrdn Physical Platinum Shares': 'Financials & Macro',
  'Abrdn Physical Silver Shares': 'Financials & Macro',
  'Affirm Holdings': 'Financials & Macro',
  'American Express': 'Financials & Macro',
  'Amplify Bitcoin 2% Monthly Option Income': 'Financials & Macro',
  'Amplify Bitcoin Max Income Covered Call': 'Financials & Macro',
  'Amplify Ethereum 3% Monthly Option Income': 'Financials & Macro',
  'Amplify Ethereum Max Income Covered Call': 'Financials & Macro',
  'Amplify Solana 3% Monthly Option Income': 'Financials & Macro',
  'Ark 21shares Bitcoin': 'Financials & Macro',
  'Barrick Gold': 'Financials & Macro',
  'Berkshire Hathaway': 'Financials & Macro',
  'Binance Coin': 'Financials & Macro',
  'Bitcoin': 'Financials & Macro',
  'Bitmine Immersion': 'Financials & Macro',
  'Bitwise Avalanche': 'Financials & Macro',
  'Bitwise Bitcoin': 'Financials & Macro',
  'Bitwise Chainlink': 'Financials & Macro',
  'Bitwise Dogecoin': 'Financials & Macro',
  'Bitwise Ethereum': 'Financials & Macro',
  'Bitwise Hyperliquid': 'Financials & Macro',
  'Bitwise Solana Staking': 'Financials & Macro',
  'Bitwise Trendwise Bitcoin And Treasuries Rotation Strategy': 'Financials & Macro',
  'Bitwise Trendwise Ether And Treasuries Rotation Strategy': 'Financials & Macro',
  'Block': 'Financials & Macro',
  'Bullish': 'Financials & Macro',
  'Canary Hbar': 'Financials & Macro',
  'Canary Litecoin': 'Financials & Macro',
  'Canary Marinade Solana': 'Financials & Macro',
  'Cardano': 'Financials & Macro',
  'Chainlink': 'Financials & Macro',
  'Ci Investments Inc Galaxy Bitcoin': 'Financials & Macro',
  'Ci Investments Inc Galaxy Ethereum': 'Financials & Macro',
  'Cipher Mining': 'Financials & Macro',
  'Circle': 'Financials & Macro',
  'CleanSpark': 'Financials & Macro',
  'Coinbase': 'Financials & Macro',
  'Coinshares Bitcoin': 'Financials & Macro',
  'Commodities': 'Financials & Macro',
  'Common': 'Financials & Macro',
  'Copper': 'Financials & Macro',
  'Crude Oil': 'Financials & Macro',
  'Currency': 'Financials & Macro',
  'Db Gold Short Etn Due February 15, 2038': 'Financials & Macro',
  'Dogecoin': 'Financials & Macro',
  'Ether': 'Financials & Macro',
  'Ether Covered Call Strategy': 'Financials & Macro',
  'Ethereum': 'Financials & Macro',
  'Evolve Funds Group Inc.': 'Financials & Macro',
  'F/m Us Treasury 3 Month Bill Fund': 'Financials & Macro',
  'Fidelity Ethereum Fund': 'Financials & Macro',
  'Fidelity Solana Fund': 'Financials & Macro',
  'Fidelity Wise Origin Bitcoin Fund': 'Financials & Macro',
  'Figure Acquisition': 'Financials & Macro',
  'Financials': 'Financials & Macro',
  'Fixed income': 'Financials & Macro',
  'Fortuna Hedged Bitcoin': 'Financials & Macro',
  'Franklin Ethereum': 'Financials & Macro',
  'Franklin Responsibly Sourced Gold': 'Financials & Macro',
  'Franklin Solana': 'Financials & Macro',
  'Franklin Templeton Digital Holdings Trust Shares Of Franklin Bitcoin': 'Financials & Macro',
  'Futu Holdings': 'Financials & Macro',
  'Galaxy Digital': 'Financials & Macro',
  'Gasoline': 'Financials & Macro',
  'Gemi Daily': 'Financials & Macro',
  'Global X Bitcoin Covered Call': 'Financials & Macro',
  'Global X Ethereum Covered Call': 'Financials & Macro',
  'Global X Investments Canada Inc. Betapro Crude Oil Inverse Leveraged Dail': 'Financials & Macro',
  'Gold': 'Financials & Macro',
  'Goldman Sachs Physical Gold Shares': 'Financials & Macro',
  'Graniteshares Bitcoin': 'Financials & Macro',
  'Graniteshares Ether': 'Financials & Macro',
  'Graniteshares Gold Trust Shares Of Beneficial Interest': 'Financials & Macro',
  'Graniteshares Platinum Shares': 'Financials & Macro',
  'Grayscale Avalanche Staking': 'Financials & Macro',
  'Grayscale Bitcoin Covered Call': 'Financials & Macro',
  'Grayscale Bitcoin Trust': 'Financials & Macro',
  'Grayscale Chainlink Trust': 'Financials & Macro',
  'Grayscale Dogecoin Trust': 'Financials & Macro',
  'Grayscale Ethereum Covered Call': 'Financials & Macro',
  'Grayscale Ethereum Staking Shares': 'Financials & Macro',
  'Grayscale Solana Staking': 'Financials & Macro',
  'Grayscale Sui Staking': 'Financials & Macro',
  'Hashdex Bitcoin': 'Financials & Macro',
  'High Yield Bonds': 'Financials & Macro',
  'Hut 8 Mining': 'Financials & Macro',
  'Invesco Currencyshares Australian Dollar Trust': 'Financials & Macro',
  'Invesco Currencyshares British Pound Sterling Trust': 'Financials & Macro',
  'Invesco Currencyshares Canadian Dollar Trust': 'Financials & Macro',
  'Invesco Currencyshares Euro Currency Trust': 'Financials & Macro',
  'Invesco Currencyshares Japanese Yen Trust': 'Financials & Macro',
  'Invesco Currencyshares Swiss Franc Trust': 'Financials & Macro',
  'Invesco Galaxy Bitcoin': 'Financials & Macro',
  'Invesco Galaxy Ethereum': 'Financials & Macro',
  'Invesco Galaxy Solana': 'Financials & Macro',
  'Investment Grade Bonds': 'Financials & Macro',
  'Iris Energy': 'Financials & Macro',
  'Ishares Bitcoin Trust': 'Financials & Macro',
  'Ishares Ethereum Trust': 'Financials & Macro',
  'Ishares Gold Trust Micro Shares': 'Financials & Macro',
  'Ishares Gold Trust Shares': 'Financials & Macro',
  'Ishares Staked Ethereum Trust': 'Financials & Macro',
  'JPMorgan Chase': 'Financials & Macro',
  'Kraneshares California Carbon Allowance Strategy': 'Financials & Macro',
  'Kurv Gold Enhanced Income': 'Financials & Macro',
  'Kurv Silver Enhanced Income': 'Financials & Macro',
  'Lemonade': 'Financials & Macro',
  'Long-term Bonds': 'Financials & Macro',
  'MARA Holdings': 'Financials & Macro',
  'Meta': 'Financials & Macro',
  'MicroStrategy': 'Financials & Macro',
  'Microsectors Gold -3x Inverse Leveraged Etns Due January 29, 2043': 'Financials & Macro',
  'Microsectors Gold 3x Leveraged Etns Due January 29, 2043': 'Financials & Macro',
  'Natural Gas': 'Financials & Macro',
  'Neos Gold High Income': 'Financials & Macro',
  'Nu Holdings': 'Financials & Macro',
  'Oscar Health': 'Financials & Macro',
  'Osprey Bitcoin Trust': 'Financials & Macro',
  'PayPal': 'Financials & Macro',
  'Proshares Bitcoin': 'Financials & Macro',
  'Proshares Ether': 'Financials & Macro',
  'Proshares K-1 Free Crude Oil': 'Financials & Macro',
  'Proshares Short Bitcoin': 'Financials & Macro',
  'Proshares Short Ether': 'Financials & Macro',
  'Proshares Ultra Bitcoin': 'Financials & Macro',
  'Proshares Ultra Bloomberg Crude Oil': 'Financials & Macro',
  'Proshares Ultra Bloomberg Natural Gas': 'Financials & Macro',
  'Proshares Ultra Copper K-1 Free': 'Financials & Macro',
  'Proshares Ultra Ether': 'Financials & Macro',
  'Proshares Ultra Euro': 'Financials & Macro',
  'Proshares Ultra Gold': 'Financials & Macro',
  'Proshares Ultra Palladium K-1 Free': 'Financials & Macro',
  'Proshares Ultra Platinum K-1 Free': 'Financials & Macro',
  'Proshares Ultra Silver': 'Financials & Macro',
  'Proshares Ultra Solana': 'Financials & Macro',
  'Proshares Ultra Yen': 'Financials & Macro',
  'Proshares Ultrashort Bitcoin': 'Financials & Macro',
  'Proshares Ultrashort Bloomberg Crude Oil': 'Financials & Macro',
  'Proshares Ultrashort Bloomberg Natural Gas': 'Financials & Macro',
  'Proshares Ultrashort Ether': 'Financials & Macro',
  'Proshares Ultrashort Euro': 'Financials & Macro',
  'Proshares Ultrashort Gold': 'Financials & Macro',
  'Proshares Ultrashort Silver': 'Financials & Macro',
  'Proshares Ultrashort Yen New': 'Financials & Macro',
  'Purpose Investments Inc. Bitcoin Cad Non Currency Hedged': 'Financials & Macro',
  'Purpose Investments Inc. Bitcoin Usd Non Currency Hedged': 'Financials & Macro',
  'Purpose Investments Inc. Ether Non Currency Hedge Unit': 'Financials & Macro',
  'Purpose Investments Inc. Silver Bullion Fd Non Currency Hedge': 'Financials & Macro',
  'Regional Banks': 'Financials & Macro',
  'Riot Platforms': 'Financials & Macro',
  'Robinhood': 'Financials & Macro',
  'Rocket Companies': 'Financials & Macro',
  'Royal Canadian Mint Exch Traded Receipt': 'Financials & Macro',
  'Short-term Bonds': 'Financials & Macro',
  'Silver': 'Financials & Macro',
  'SoFi Technologies': 'Financials & Macro',
  'Solana': 'Financials & Macro',
  'Spdr Gold Minishares Trust': 'Financials & Macro',
  'Sprott Physical Copper Trust': 'Financials & Macro',
  'Stellar': 'Financials & Macro',
  'Sui': 'Financials & Macro',
  'T-Bills': 'Financials & Macro',
  'TeraWulf': 'Financials & Macro',
  'Teucrium 2x Daily Corn': 'Financials & Macro',
  'Teucrium 2x Daily Wheat': 'Financials & Macro',
  'Teucrium Corn Fund Etv': 'Financials & Macro',
  'Teucrium Soybean Fund Etv': 'Financials & Macro',
  'Teucrium Sugar Fund Etv': 'Financials & Macro',
  'Teucrium Wheat Fund Etv': 'Financials & Macro',
  'Total Bond Market': 'Financials & Macro',
  'United States 12 Month Natural Gas Fund': 'Financials & Macro',
  'United States 12 Month Oil': 'Financials & Macro',
  'United States Brent Oil Fund, Lp Etv': 'Financials & Macro',
  'Upstart Holdings': 'Financials & Macro',
  'Uranium': 'Financials & Macro',
  'Us Treasury 10 Year Note': 'Financials & Macro',
  'Us Treasury 12 Month Bill': 'Financials & Macro',
  'Us Treasury 2 Year Note': 'Financials & Macro',
  'Us Treasury 20 Year Bond': 'Financials & Macro',
  'Us Treasury 3 Year Note': 'Financials & Macro',
  'Us Treasury 30 Year Bond': 'Financials & Macro',
  'Us Treasury 5 Year Note': 'Financials & Macro',
  'Us Treasury 6 Month Bill': 'Financials & Macro',
  'Us Treasury 7 Year Note': 'Financials & Macro',
  'Vaneck Avalanche': 'Financials & Macro',
  'Vaneck Bitcoin Trust': 'Financials & Macro',
  'Vaneck Ethereum': 'Financials & Macro',
  'Vaneck Merk Gold': 'Financials & Macro',
  'Vaneck Solana': 'Financials & Macro',
  'Webull': 'Financials & Macro',
  'Wisdomtree Bitcoin Fund': 'Financials & Macro',
  'XRP': 'Financials & Macro',
  'eToro': 'Financials & Macro',
  // --- Technology ---
  'AMD': 'Technology',
  'ASML': 'Technology',
  'AST SpaceMobile': 'Technology',
  'AXT Inc.': 'Technology',
  'Adobe': 'Technology',
  'Amkor Technology': 'Technology',
  'Amphenol': 'Technology',
  'Amprius Technologies': 'Technology',
  'AppLovin': 'Technology',
  'Apple': 'Technology',
  'Applied Digital': 'Technology',
  'Applied Materials': 'Technology',
  'Applied Optoelectronics': 'Technology',
  'Arista Networks': 'Technology',
  'Arm Holdings': 'Technology',
  'Astera Labs': 'Technology',
  'Baidu': 'Technology',
  'BigBear.ai': 'Technology',
  'Broadcom': 'Technology',
  'C3.ai': 'Technology',
  'Celestica': 'Technology',
  'Cerebras Systems': 'Technology',
  'Ciena': 'Technology',
  'Cisco': 'Technology',
  'Cloudflare': 'Technology',
  'Coherent': 'Technology',
  'Core Scientific': 'Technology',
  'CoreWeave': 'Technology',
  'Corning': 'Technology',
  'Credo Technology': 'Technology',
  'CrowdStrike': 'Technology',
  'D-Wave Quantum': 'Technology',
  'Dell Technologies': 'Technology',
  'Disney': 'Technology',
  'Duolingo': 'Technology',
  'EchoStar': 'Technology',
  'Flywire': 'Technology',
  'Fortress Transportation': 'Technology',
  'Google': 'Technology',
  'IBM': 'Technology',
  'Information technology': 'Technology',
  'Intel': 'Technology',
  'IonQ': 'Technology',
  'KLA Corp': 'Technology',
  'Keel': 'Technology',
  'Lam Research': 'Technology',
  'Lumentum Holdings': 'Technology',
  'Marvell Technology': 'Technology',
  'Micron Technology': 'Technology',
  'Microsoft': 'Technology',
  'Monolithic Power': 'Technology',
  'NVIDIA': 'Technology',
  'Navitas Semiconductor': 'Technology',
  'Nbis Daily': 'Technology',
  'Netflix': 'Technology',
  'Nokia': 'Technology',
  'Okta': 'Technology',
  'Ondas Inc.': 'Technology',
  'Oracle': 'Technology',
  'Palantir Technologies': 'Technology',
  'Palo Alto Networks': 'Technology',
  'Poet Technologies': 'Technology',
  'Pony.ai': 'Technology',
  'Qualcomm': 'Technology',
  'Quantum Computing': 'Technology',
  'Reddit': 'Technology',
  'Rigetti Computing': 'Technology',
  'Roblox': 'Technology',
  'Salesforce': 'Technology',
  'SanDisk': 'Technology',
  'Sap Se': 'Technology',
  'Seagate Technology': 'Technology',
  'Semiconductors': 'Technology',
  'ServiceNow': 'Technology',
  'Shopify': 'Technology',
  'Snap Inc.': 'Technology',
  'Snowflake': 'Technology',
  'SoundHound AI': 'Technology',
  'Spotify': 'Technology',
  'Stmicroelectronics Nv': 'Technology',
  'Super Micro Computer': 'Technology',
  'Taiwan Semiconductor': 'Technology',
  'Tech': 'Technology',
  'Tempus AI': 'Technology',
  'Teradyne': 'Technology',
  'Texas Instruments': 'Technology',
  'The Trade Desk': 'Technology',
  'Trump Media & Tech': 'Technology',
  'UiPath': 'Technology',
  'Unity Software': 'Technology',
  'Vertiv': 'Technology',
  'Western Digital': 'Technology',
  'Xndu Daily': 'Technology',
  'Zeta Global': 'Technology',
};

// Quadrants assignment
export const categoryCentroids = {
  'Technology': { x: 240, y: 150, label: 'Technology', color: 'border-indigo-500/20 text-indigo-400' },
  'Financials & Macro': { x: 720, y: 150, label: 'Financials & Macro', color: 'border-purple-500/20 text-purple-400' },
  'Energy & Industrials': { x: 240, y: 410, label: 'Energy & Industrials', color: 'border-emerald-500/20 text-emerald-400' },
  'Consumer & Others': { x: 720, y: 410, label: 'Consumer & Others', color: 'border-amber-500/20 text-amber-400' }
};

export const defaultCategory = 'Consumer & Others';
